temp: pin bootstrap@4.6.1 to fix $transition-collapse-width error
Newer versions of Bootstrap cause the following error in
frontend-app-payment:

    ERROR in ./example/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[4]!./example/index.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Undefined variable.
       ╷
    24 │     @include transition($transition-collapse-width);
       │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
       ╵
      node_modules/bootstrap/scss/_transitions.scss 24:25  @import
      node_modules/@edx/paragon/scss/core/core.scss 8:9    @import
      example/index.scss 3:9                               root stylesheet

This has been fixed in Paragon 20.9.2. See
https://github.com/openedx/paragon/pull/1562. But we cannot upgrade to
that version of Paragon yet due to a bug in how we use <Dropdown.Toggle>
in frontend-component-header-edx. See previous commit for more details.